# Generated by Django 6.1 on 2026-08-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='available',
            new_name='is_available',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='plate_number',
            new_name='license_plate',
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Nissan', 'Nissan'), ('Hyundai', 'Hyundai'), ('Other', 'Other')], max_length=50),
        ),
    ]
