# Generated by Django 6.1 on 2026-08-19 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_created_at_car_description_car_fuel_car_seats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(default='Luxury car available for rent'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(default='Petrol', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(default='Automatic', max_length=50),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(max_length=254)),
                ('pickup_date', models.DateField()),
                ('return_date', models.DateField()),
                ('message', models.TextField(blank=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
    ]
